// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  GetAllArticlesError,
  GetAllArticlesResponse,
  GetArticleData,
  GetArticleError,
  GetArticleResponse,
  ListAllArticlesError,
  ListAllArticlesResponse,
  ListAllArticlesData,
} from "./types.gen";

export const client = createClient(createConfig());

export class StoreArticleService {
  public static getStoreArticles<ThrowOnError extends boolean = false>(
    options?: Options<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetAllArticlesResponse,
      GetAllArticlesError,
      ThrowOnError
    >({
      ...options,
      url: "/_api/store/articles",
    });
  }

  public static getStoreArticlesById<ThrowOnError extends boolean = false>(
    options: Options<GetArticleData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetArticleResponse,
      GetArticleError,
      ThrowOnError
    >({
      ...options,
      url: "/_api/store/articles/{articleId}",
    });
  }
}

export class CompanyArticleService {
  public static getCompanyArticles<ThrowOnError extends boolean = false>(
    options?: Options<ListAllArticlesData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ListAllArticlesResponse,
      ListAllArticlesError,
      ThrowOnError
    >({
      ...options,
      url: "/_api/company/articles",
    });
  }

  public static getCompanyArticlesById<ThrowOnError extends boolean = false>(
    options: Options<GetArticleData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetArticleResponse,
      GetArticleError,
      ThrowOnError
    >({
      ...options,
      url: "/_api/company/articles/{articleId}",
    });
  }
}

export class PersonalArticleService {
  public static getArticles<ThrowOnError extends boolean = false>(
    options?: Options<ListAllArticlesData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ListAllArticlesResponse,
      ListAllArticlesError,
      ThrowOnError
    >({
      ...options,
      url: "/_api/articles",
    });
  }

  public static getArticlesById<ThrowOnError extends boolean = false>(
    options: Options<GetArticleData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetArticleResponse,
      GetArticleError,
      ThrowOnError
    >({
      ...options,
      url: "/_api/articles/{articleId}",
    });
  }
}
