// This file is auto-generated by @hey-api/openapi-ts

export type AuditPointModel = {
  by: string;
  at: string;
};

export type StoreInfo = {
  teamId: string;
  storeId: string;
};

export type CompanyArticleStoreInfoModel = {
  storeId: string;
  teamId: string;
};

export type CompanyArticleInformationsModel = {
  displayName: string;
  isDeployed: boolean;
  isHome: boolean;
  created: AuditPointModel;
  lastModified: AuditPointModel;
};

export type CompanyArticleModel = {
  id: string;
  infos: CompanyArticleInformationsModel;
  storeInfo: Array<CompanyArticleStoreInfoModel>;
};

export type Configuration = {
  id: string;
  clientId: string;
  iconId: string;
  appPath: string;
  appName: string;
  primaryColor: string;
};

export type Contributor = {
  memberId?: string;
  type?: MemberType;
};

export type MemberType = "user" | "group";

export type PersonalArticleInformationsModel = {
  displayName: string;
  created: AuditPointModel;
  lastModified: AuditPointModel;
};

export type PersonalArticleModel = {
  id: string;
  isPersonal: boolean;
  isEditable: boolean;
  isHome: boolean;
  infos: PersonalArticleInformationsModel;
};

export type GetAllArticlesResponse = Array<CompanyArticleModel>;

export type GetAllArticlesError = unknown;

export type GetArticleData = {
  path: {
    articleId: string;
  };
};

export type GetArticleResponse = CompanyArticleModel;

export type GetArticleError = unknown;

export type ListAllArticlesResponse = Array<CompanyArticleModel>;

export type ListAllArticlesError = unknown;

export type ListAllArticlesData = {
  query?: {
    includeWidgets?: boolean;
  };
};
